/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;

import static org.junit.Assert.assertEquals;

public class ReduceTest {
    @Test (expected = IllegalArgumentException.class)
    public void JoinShouldThrowExceptionIfNull() {
        Reduce.join(null);

    }

    @Test
    public void JoinshouldReturnAnEmptyStringIfListIsEmpty() {

        assertEquals("",Reduce.join(Collections.emptyList()));

    }

    @Test
    public void JoinShouldReturnTheStringContainedInIndex0OfArray() {

        assertEquals("Hello", Reduce.join(Arrays.asList("Hello")));


    }

    @Test
    public void JoinShouldReturnAStringContainingMultipleStringDeliminatedBySpace() {

        assertEquals("Hello World",Reduce.join(Arrays.asList("Hello","World")));

    }

    @Test
    public void JoinSHouldReturnAStringContainingMultipleStringDeliminatedByParamter() {

        assertEquals("Hello, Bob", Reduce.join(Arrays.asList("Hello", "Bob"), ", "));



    }

    @Test (expected = IllegalArgumentException.class)
    public void wordCountsShouldThrowExceptionIfNull() {
        Reduce.wordCounts(null);
    }

    @Test
    public void wordCountShouldReturnAnEmptyMapWhenPassedAnEmptyString() {

        assertEquals(Collections.emptyMap(), Reduce.wordCounts(""));




    }





}


