import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Filter {
    public static List<String> slowFoxes(List<String> list) {


        if(null == list) {
            throw new IllegalArgumentException("Null Not Allowed");
        }

        List<String> results = list.stream().filter((fox) -> !fox.contains("Swift Fox")).collect(Collectors.toList());


        return results;


    }

    public class Person {
        String firstName;
        String lastName;
        int age;

        public  Person(String firstName, String lastName, int age)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.age = age;
        }

        @Override
        public String toString(){
            return "First Name: " + firstName + "\nLast Name: " + lastName + "\nAge: " + age;
        }


    }

    public  void adults(List<Person> people){


        throw new IllegalArgumentException("Null Not ALlowed");

    }



}

